# Generated by Django 5.1.6 on 2025-06-04 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('INTEGRITY', 'Data Integrity Violations'), ('PATTERN', 'Unusual Data Patterns'), ('MODIFICATION', 'Data Modification Patterns'), ('VOLUME', 'Data Volume Anomalies'), ('AGGREGATE', 'Aggregate Calculations')], max_length=20)),
                ('rule_criteria', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_system_rule', models.BooleanField(default=True)),
                ('aggregate_operation', models.CharField(blank=True, choices=[('SUM', 'Sum'), ('AVG', 'Average'), ('MAX', 'Maximum'), ('MIN', 'Minimum')], max_length=3, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('table_name', models.CharField(max_length=255)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='AlertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=255)),
                ('alert_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='data_monitoring_app.rulemodel')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
            },
        ),
    ]
