# Generated by Django 5.1.6 on 2025-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertmodel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rulemodel',
            name='aggregate_operation',
        ),
        migrations.RemoveField(
            model_name='rulemodel',
            name='column_name',
        ),
        migrations.RemoveField(
            model_name='rulemodel',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='rulemodel',
            name='threshold_value',
        ),
        migrations.AddField(
            model_name='alertmodel',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alertmodel',
            name='alert_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='rule_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='rule_type',
            field=models.CharField(choices=[('INTEGRITY', 'Data Integrity Violations'), ('PATTERN', 'Unusual Data Patterns'), ('MODIFICATION', 'Data Modification Patterns'), ('VOLUME', 'Data Volume Anomalies'), ('AGGREGATE', 'Aggregate Threshold')], max_length=20),
        ),
    ]
