# Generated by Django 5.1.6 on 2025-06-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_monitoring_app', '0002_remove_alertmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertModel',
        ),
        migrations.DeleteModel(
            name='RuleModel',
        ),
    ]
